# 10.3 word2vec的实现

In [1]:
import collections
import math
import random
import sys
import time
import os
import numpy as np
import torch
from torch import nn
import torch.utils.data as Data

sys.path.append("..") 
import d2lzh_pytorch as d2l
print(torch.__version__)

1.2.0+cu92


## 10.3.1 处理数据集

In [2]:
assert 'ptb.train.txt' in os.listdir("../../data/ptb")

In [3]:
with open('../../data/ptb/ptb.train.txt', 'r') as f:
    lines = f.readlines()
    # st是sentence的缩写
    raw_dataset = [st.split() for st in lines]

'# sentences: %d' % len(raw_dataset)

'# sentences: 42068'

In [4]:
for st in raw_dataset[:3]:
    print('# tokens:', len(st), st[:5])

# tokens: 24 ['aer', 'banknote', 'berlitz', 'calloway', 'centrust']
# tokens: 15 ['pierre', '<unk>', 'N', 'years', 'old']
# tokens: 11 ['mr.', '<unk>', 'is', 'chairman', 'of']


### 10.3.1.1 建立词语索引

In [5]:
# tk是token的缩写
counter = collections.Counter([tk for st in raw_dataset for tk in st])
counter = dict(filter(lambda x: x[1] >= 5, counter.items()))

In [6]:
idx_to_token = [tk for tk, _ in counter.items()] #idx_to_token使用列表即可
token_to_idx = {tk: idx for idx, tk in enumerate(idx_to_token)}
dataset = [[token_to_idx[tk] for tk in st if tk in token_to_idx]
           for st in raw_dataset]
num_tokens = sum([len(st) for st in dataset])
'# tokens: %d' % num_tokens

'# tokens: 887100'

### 10.3.1.2 二次采样

In [7]:
def discard(idx):
    return random.uniform(0, 1) < 1 - math.sqrt(
        1e-4 / counter[idx_to_token[idx]] * num_tokens)

subsampled_dataset = [[tk for tk in st if not discard(tk)] for st in dataset]
'# tokens: %d' % sum([len(st) for st in subsampled_dataset])

'# tokens: 375488'

In [8]:
def compare_counts(token):
    return '# %s: before=%d, after=%d' % (token, sum(
        [st.count(token_to_idx[token]) for st in dataset]), sum(
        [st.count(token_to_idx[token]) for st in subsampled_dataset]))

compare_counts('the')#“the”的采样率不足1/20

'# the: before=50770, after=2077'

In [9]:
compare_counts('join')#低频词“join”则完整地保留了下来

'# join: before=45, after=45'

### 10.3.1.3 提取中心词和背景词

In [10]:
def get_centers_and_contexts(dataset, max_window_size):
    centers, contexts = [], []
    for st in dataset:
        if len(st) < 2:  # 每个句子至少要有2个词才可能组成一对“中心词-背景词”
            continue
        centers += st
        for center_i in range(len(st)):
            #在整数1和max_window_size（最大背景窗口）之间随机均匀采样一个整数作为背景窗口大小
            window_size = random.randint(1, max_window_size)
            indices = list(range(max(0, center_i - window_size),
                                 min(len(st), center_i + 1 + window_size)))#注意边界
            indices.remove(center_i)  # 将中心词排除在背景词之外
            contexts.append([st[idx] for idx in indices])
    return centers, contexts

In [11]:
tiny_dataset = [list(range(7)), list(range(7, 10))]
print('dataset', tiny_dataset)
for center, context in zip(*get_centers_and_contexts(tiny_dataset, 2)):
    print('center', center, 'has contexts', context)

dataset [[0, 1, 2, 3, 4, 5, 6], [7, 8, 9]]
center 0 has contexts [1, 2]
center 1 has contexts [0, 2]
center 2 has contexts [1, 3]
center 3 has contexts [2, 4]
center 4 has contexts [3, 5]
center 5 has contexts [3, 4, 6]
center 6 has contexts [5]
center 7 has contexts [8, 9]
center 8 has contexts [7, 9]
center 9 has contexts [7, 8]


In [12]:
all_centers, all_contexts = get_centers_and_contexts(subsampled_dataset, 5)

## 10.3.2 负采样
根据word2vec论文的建议，噪声词采样概率P(w)设为w词频与总词频之比的0.75次方

In [13]:
def get_negatives(all_contexts, sampling_weights, K):
    all_negatives, neg_candidates, i = [], [], 0
    population = list(range(len(sampling_weights)))
    for contexts in all_contexts:
        negatives = []
        while len(negatives) < len(contexts) * K: #噪声词为背景词的K倍，背景词长度不定，所以噪声词长度也不定
            if i == len(neg_candidates): #如果候选噪声词用完了，生成新的候选噪声词
                # 根据每个词的权重（sampling_weights）随机生成k个词的索引作为候选噪声词。
                # 为了高效计算，可以将k设得稍大一点（每次生成多一点候选词，就可以少生成几次）
                i, neg_candidates = 0, random.choices(
                    population, sampling_weights, k=int(1e5))#按权重采样
            neg, i = neg_candidates[i], i + 1
            # 噪声词不能是背景词
            if neg not in set(contexts):
                negatives.append(neg)
        all_negatives.append(negatives)
    return all_negatives

sampling_weights = [counter[w]**0.75 for w in idx_to_token]
all_negatives = get_negatives(all_contexts, sampling_weights, 5)

## 10.3.3 读取数据
手写自己的数据集和batch函数

In [14]:
def batchify(data):
    """用作DataLoader的参数collate_fn: 输入是个长为batchsize的list, list中的每个元素都是__getitem__得到的结果"""
    max_len = max(len(c) + len(n) for _, c, n in data)
    centers, contexts_negatives, masks, labels = [], [], [], [] #masks用于区分填充项，labels用于区分正类、负类
    for center, context, negative in data:
        cur_len = len(context) + len(negative)
        centers += [center]
        contexts_negatives += [context + negative + [0] * (max_len - cur_len)]#padding
        masks += [[1] * cur_len + [0] * (max_len - cur_len)] #标出填充项
        labels += [[1] * len(context) + [0] * (max_len - len(context))]#标出正例
    return (torch.tensor(centers).view(-1, 1), torch.tensor(contexts_negatives),
            torch.tensor(masks), torch.tensor(labels))

In [15]:
class MyDataset(torch.utils.data.Dataset):
    def __init__(self, centers, contexts, negatives):
        assert len(centers) == len(contexts) == len(negatives)
        self.centers = centers
        self.contexts = contexts
        self.negatives = negatives
        
    def __getitem__(self, index):
        return (self.centers[index], self.contexts[index], self.negatives[index])

    def __len__(self):
        return len(self.centers)

batch_size = 512
num_workers = 0 if sys.platform.startswith('win32') else 4

dataset = MyDataset(all_centers, 
                    all_contexts, 
                    all_negatives)
data_iter = Data.DataLoader(dataset, batch_size, shuffle=True,
                            collate_fn=batchify, 
                            num_workers=num_workers)
for batch in data_iter:
    #batch是包含'centers', 'contexts_negatives', 'masks','labels'变量的元组
    for name, data in zip(['centers', 'contexts_negatives', 'masks',
                           'labels'], batch):
        print(name, 'shape:', data.shape)
    break

centers shape: torch.Size([512, 1])
contexts_negatives shape: torch.Size([512, 60])
masks shape: torch.Size([512, 60])
labels shape: torch.Size([512, 60])


## 10.3.4 跳字模型
### 10.3.4.1 嵌入层

In [16]:
embed = nn.Embedding(num_embeddings=20, embedding_dim=4)
embed.weight

Parameter containing:
tensor([[-0.4863,  0.1729, -0.5778,  0.3978],
        [-0.5260,  1.6138,  0.9068,  0.0973],
        [-1.4360, -0.3743,  0.2999, -0.3867],
        [-0.4398, -1.1948,  2.4538,  0.4158],
        [-0.4327,  1.5601, -0.4529, -1.2438],
        [ 0.3703, -0.4655,  0.4970, -1.6633],
        [-0.0321, -0.5785, -1.4204,  2.0082],
        [-0.2044, -0.5584,  0.0889,  0.3419],
        [-2.3694, -0.7425, -0.5074, -0.2927],
        [ 0.7399, -0.5203,  0.8526, -0.3015],
        [-0.5172, -1.1536,  0.7029, -1.1475],
        [-1.3861, -1.8314,  1.1657, -0.4067],
        [-0.0424,  0.8320,  0.5300, -0.6879],
        [-0.0167,  0.5317,  0.0475, -0.0135],
        [ 0.6912,  0.6537,  1.5235, -0.5544],
        [ 0.5359, -1.1926,  0.6792,  0.2474],
        [ 0.2702, -0.5854,  0.3996,  0.6228],
        [-0.3032,  0.7556, -0.0940,  0.9730],
        [ 0.1980,  0.0566, -0.8091, -1.1695],
        [-0.0240,  0.5768, -2.1735, -0.0716]], requires_grad=True)

In [17]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.long)
embed(x)

tensor([[[-0.5260,  1.6138,  0.9068,  0.0973],
         [-1.4360, -0.3743,  0.2999, -0.3867],
         [-0.4398, -1.1948,  2.4538,  0.4158]],

        [[-0.4327,  1.5601, -0.4529, -1.2438],
         [ 0.3703, -0.4655,  0.4970, -1.6633],
         [-0.0321, -0.5785, -1.4204,  2.0082]]], grad_fn=<EmbeddingBackward>)

### 10.3.4.2 小批量乘法

In [18]:
X = torch.ones((2, 1, 4))
Y = torch.ones((2, 4, 6))
torch.bmm(X, Y).shape

torch.Size([2, 1, 6])

### 10.3.4.3 跳字模型前向计算

In [19]:
def skip_gram(center, contexts_and_negatives, embed_v, embed_u):
    v = embed_v(center)
    u = embed_u(contexts_and_negatives)
    pred = torch.bmm(v, u.permute(0, 2, 1)) #(bacth_size,1,embedding_dim)*(batch_size,embedding_dim,max_len)
    return pred #(batch_size,1,max_len)

## 10.3.5 训练模型
### 10.3.5.1 二元交叉熵损失函数

In [20]:
class SigmoidBinaryCrossEntropyLoss(nn.Module):
    def __init__(self): # none mean sum
        super(SigmoidBinaryCrossEntropyLoss, self).__init__()
    def forward(self, inputs, targets, mask=None):
        """
        input – Tensor shape: (batch_size, len)
        target – Tensor of the same shape as input
        """
        inputs, targets, mask = inputs.float(), targets.float(), mask.float()
        #'none': no reduction will be applied,会保留每个样本的loss
        res = nn.functional.binary_cross_entropy_with_logits(inputs, targets, reduction="none", weight=mask)
        return res.mean(dim=1)

loss = SigmoidBinaryCrossEntropyLoss()

In [21]:
pred = torch.tensor([[1.5, 0.3, -1, 2], [1.1, -0.6, 2.2, 0.4]])
# 标签变量label中的1和0分别代表背景词(正类）和噪声词（负类）
label = torch.tensor([[1, 0, 0, 0], [1, 1, 0, 0]])
mask = torch.tensor([[1, 1, 1, 1], [1, 1, 1, 0]])  # 掩码变量
print( mask.shape[1])#4
print(mask.float().sum(dim=1))#tensor([4., 3.])
print(loss(pred, label, mask))#tensor([0.8740, 0.9075])
loss(pred, label, mask) * mask.shape[1] / mask.float().sum(dim=1)#掩码变量可用于避免填充项对损失函数计算的影响

4
tensor([4., 3.])
tensor([0.8740, 0.9075])


tensor([0.8740, 1.2100])

In [22]:
def sigmd(x):
    return - math.log(1 / (1 + math.exp(-x)))

print('%.4f' % ((sigmd(1.5) + sigmd(-0.3) + sigmd(1) + sigmd(-2)) / 4)) # 注意1-sigmoid(x) = sigmoid(-x)
print('%.4f' % ((sigmd(1.1) + sigmd(-0.6) + sigmd(-2.2)) / 3))#mask为0的不计算

0.8740
1.2100


### 10.3.5.2 初始化模型参数

In [23]:
embed_size = 100
net = nn.Sequential(
    #注意：两个嵌入层分别是中心词和背景词的嵌入层，是两个不同的嵌入层，只是维度相同而已
    nn.Embedding(num_embeddings=len(idx_to_token), embedding_dim=embed_size),
    nn.Embedding(num_embeddings=len(idx_to_token), embedding_dim=embed_size)
)

### 10.3.5.3 定义训练函数

In [24]:
def train(net, lr, num_epochs):
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    print("train on", device)
    net = net.to(device)
    optimizer = torch.optim.Adam(net.parameters(), lr=lr)
    for epoch in range(num_epochs):
        start, l_sum, n = time.time(), 0.0, 0
        for batch in data_iter:
            center, context_negative, mask, label = [d.to(device) for d in batch]
            
            pred = skip_gram(center, context_negative, net[0], net[1]) #即u*v, 形状为(batch_size,1,max_len)
            #print(pred.view(label.shape).shape) 把pred维度变为(batch_size,max_len)
            # 使用掩码变量mask来避免填充项对损失函数计算的影响
            l = (loss(pred.view(label.shape), label, mask) *
                 mask.shape[1] / mask.float().sum(dim=1)).mean() # 一个batch的平均loss
            optimizer.zero_grad()
            l.backward()
            optimizer.step()
            l_sum += l.cpu().item()
            n += 1
        print('epoch %d, loss %.2f, time %.2fs'
              % (epoch + 1, l_sum / n, time.time() - start))#l_sum / n每轮训练后所有批次的平均损失

In [25]:
train(net, 0.01, 10)

train on cuda
epoch 1, loss 1.97, time 3.01s
epoch 2, loss 0.62, time 2.87s
epoch 3, loss 0.45, time 2.85s
epoch 4, loss 0.40, time 2.88s
epoch 5, loss 0.37, time 2.85s
epoch 6, loss 0.35, time 2.84s
epoch 7, loss 0.34, time 2.87s
epoch 8, loss 0.33, time 2.88s
epoch 9, loss 0.32, time 2.86s
epoch 10, loss 0.32, time 2.85s


## 10.3.6 应用词嵌入模型

In [27]:
def get_similar_tokens(query_token, k, embed):
    W = embed.weight.data
    x = W[token_to_idx[query_token]]
    # 添加的1e-9是为了数值稳定性
    cos = torch.matmul(W, x) / (torch.sum(W * W, dim=1) * torch.sum(x * x) + 1e-9).sqrt() #余弦相似度
    _, topk = torch.topk(cos, k=k+1) #+1是因为后面要除去输入词
    topk = topk.cpu().numpy()
    for i in topk[1:]:  # 除去输入词
        print('cosine sim=%.3f: %s' % (cos[i], (idx_to_token[i])))
        
get_similar_tokens('chip', 3, net[0])

cosine sim=0.454: chromosome
cosine sim=0.446: intel
cosine sim=0.410: product
